name: codable_dart
description: A codable protocol for Dart.
version: 0.1.0-beta.0
repository: https://github.com/schultek/codable

environment:
  sdk: ^3.5.0

topics:
  - codable
  - serialization
  - json

dependencies:
  # TODO: Replace with own implementation
  crimson: ^0.3.1

dev_dependencies:
  collection: ^1.19.1
  lints: ^4.0.0
  test: ^1.24.0
  type_plus: ^2.1.1
